global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: app
    static_configs:
      - targets: ["app:3000"]
  
  - job_name: postgresql
    static_configs:
      - targets: ['postgresql-exporter:9187']